DEBUG 2020-02-26 00:50:34.159 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-02-26 00:50:34.176 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-02-26 00:50:34.177 UTC: 	 Executing command: 'status'
DEBUG 2020-02-26 00:50:34.178 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
DEBUG 2020-03-09 19:28:19.653 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-03-09 19:28:19.668 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-03-09 19:28:19.669 UTC: 	 Executing command: 'status'
DEBUG 2020-03-09 19:28:19.669 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
ERROR 2020-03-09 19:28:19.672 UTC: 	 Error: ../crab_projects/crab_TnP_SingleMuon2017C_jpsi is not a valid CRAB project directory.
ERROR 2020-03-09 19:28:19.672 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 277, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 595, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: ../crab_projects/crab_TnP_SingleMuon2017C_jpsi is not a valid CRAB project directory.
DEBUG 2021-01-11 17:26:05.857 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-11 17:26:05.857 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-11 17:26:05.857 UTC: 	 Executing command: 'status'
DEBUG 2021-01-11 17:26:05.858 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
ERROR 2021-01-11 17:26:05.906 UTC: 	 Error: ../crab_projects/crab_TnP_JpsiPt82016_jpsi is not a valid CRAB project directory.
ERROR 2021-01-11 17:26:05.906 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: ../crab_projects/crab_TnP_JpsiPt82016_jpsi is not a valid CRAB project directory.
INFO 2021-01-11 17:26:05.908 UTC: 	 Log file is /home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/crab.log
DEBUG 2021-01-11 17:28:47.246 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-11 17:28:47.246 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-11 17:28:47.246 UTC: 	 Executing command: 'status'
DEBUG 2021-01-11 17:28:47.247 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
ERROR 2021-01-11 17:28:47.250 UTC: 	 Error: ../crab_projects/crab_TnP_JpsiPt82016_jpsi is not a valid CRAB project directory.
ERROR 2021-01-11 17:28:47.250 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: ../crab_projects/crab_TnP_JpsiPt82016_jpsi is not a valid CRAB project directory.
INFO 2021-01-11 17:28:47.253 UTC: 	 Log file is /home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/crab.log
DEBUG 2021-01-26 16:31:07.329 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-26 16:31:07.329 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-26 16:31:07.329 UTC: 	 Executing command: 'status'
DEBUG 2021-01-26 16:31:07.330 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
ERROR 2021-01-26 16:31:07.333 UTC: 	 Error: ../crab_projects/crab_TnP_Charmonium2018B_jpsi is not a valid CRAB project directory.
ERROR 2021-01-26 16:31:07.333 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: ../crab_projects/crab_TnP_Charmonium2018B_jpsi is not a valid CRAB project directory.
INFO 2021-01-26 16:31:07.337 UTC: 	 Log file is /home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/crab.log
DEBUG 2021-01-26 16:31:16.408 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-26 16:31:16.409 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-26 16:31:16.409 UTC: 	 Executing command: 'status'
DEBUG 2021-01-26 16:31:16.409 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
ERROR 2021-01-26 16:31:16.411 UTC: 	 Error: ../crab_projects/crab_TnP_Charmonium2018B_jpsi is not a valid CRAB project directory.
ERROR 2021-01-26 16:31:16.411 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: ../crab_projects/crab_TnP_Charmonium2018B_jpsi is not a valid CRAB project directory.
INFO 2021-01-26 16:31:16.415 UTC: 	 Log file is /home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/crab.log
