DEBUG 2020-03-11 00:09:50.177 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-03-11 00:09:50.192 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-03-11 00:09:50.192 UTC: 	 Executing command: 'submit'
DEBUG 2020-03-11 00:09:50.193 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
DEBUG 2020-03-11 00:09:50.202 UTC: 	 Checking credentials
DEBUG 2020-03-11 00:09:50.203 UTC: 	 Found proxy file /tmp/x509up_u5729
DEBUG 2020-03-11 00:09:50.203 UTC: 	 Getting proxy life time left
DEBUG 2020-03-11 00:09:50.307 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u5729 -timeleft
 output : 32594

 error: 
 retcode : 0
DEBUG 2020-03-11 00:09:50.411 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u5729 -actimeleft
 output : 32594

 error: 
 retcode : 0
DEBUG 2020-03-11 00:09:50.412 UTC: 	 Proxy valid for 09:03:14 hours
INFO 2020-03-11 00:09:50.412 UTC: 	 Will use CRAB configuration file zmumudata_crab.py
DEBUG 2020-03-11 00:09:50.412 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-03-11 00:09:50.421 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-03-11 00:09:50.422 UTC: 	 Working area '/home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/crab_projects/crab_TnP_SingleMuon2017C_zmumu' already exists 
Please change the requestName in the config file
ERROR 2020-03-11 00:09:50.422 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 418, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/crab_projects/crab_TnP_SingleMuon2017C_zmumu' already exists 
Please change the requestName in the config file
DEBUG 2020-09-02 21:13:46.756 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-09-02 21:13:46.756 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-09-02 21:13:46.756 UTC: 	 Executing command: 'submit'
DEBUG 2020-09-02 21:13:46.757 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
INFO 2020-09-02 21:13:46.795 UTC: 	 Will use CRAB configuration file zmumudata_crab.py
DEBUG 2020-09-02 21:13:46.795 UTC: 	 Loading CRAB configuration file.
ERROR 2020-09-02 21:13:46.852 UTC: 	 Error while loading CRAB configuration:
cannot import name getUsernameFromSiteDB
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-09-02 21:13:46.852 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
cannot import name getUsernameFromSiteDB
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-09-02 21:13:46.855 UTC: 	 Log file is /home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/ZmumuData/crab.log
DEBUG 2021-01-12 20:32:24.883 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-12 20:32:24.883 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-12 20:32:24.883 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-12 20:32:24.884 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
ERROR 2021-01-12 20:32:24.939 UTC: 	 CRAB configuration file crabConfig.py not found.
ERROR 2021-01-12 20:32:24.939 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 312, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabConfig.py not found.
INFO 2021-01-12 20:32:24.942 UTC: 	 Log file is /home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/ZmumuData/crab.log
DEBUG 2021-01-12 20:32:45.630 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-12 20:32:45.630 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-12 20:32:45.630 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-12 20:32:45.630 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
ERROR 2021-01-12 20:32:45.632 UTC: 	 CRAB configuration file crabConfig.py not found.
ERROR 2021-01-12 20:32:45.632 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 312, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabConfig.py not found.
INFO 2021-01-12 20:32:45.635 UTC: 	 Log file is /home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/ZmumuData/crab.log
DEBUG 2021-01-12 20:32:56.310 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-12 20:32:56.311 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-12 20:32:56.311 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-12 20:32:56.311 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
ERROR 2021-01-12 20:32:56.312 UTC: 	 CRAB configuration file crabConfig.py not found.
ERROR 2021-01-12 20:32:56.312 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 312, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabConfig.py not found.
INFO 2021-01-12 20:32:56.315 UTC: 	 Log file is /home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/ZmumuData/crab.log
DEBUG 2021-01-12 20:38:13.774 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-12 20:38:13.774 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-12 20:38:13.774 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-12 20:38:13.775 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
ERROR 2021-01-12 20:38:13.777 UTC: 	 CRAB configuration file crabConfig.py not found.
ERROR 2021-01-12 20:38:13.777 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 312, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 52, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file crabConfig.py not found.
INFO 2021-01-12 20:38:13.780 UTC: 	 Log file is /home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/ZmumuData/crab.log
DEBUG 2021-01-12 20:43:02.459 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-12 20:43:02.459 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-12 20:43:02.459 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-12 20:43:02.460 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
INFO 2021-01-12 20:43:02.462 UTC: 	 Will use CRAB configuration file zmumudata_crab_2016.py
DEBUG 2021-01-12 20:43:02.462 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-01-12 20:43:02.474 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-01-12 20:43:02.475 UTC: 	 Working area '/home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/crab_projects/crab_TnP_SingleMuon2016C_zmumu' already exists 
Please change the requestName in the config file
ERROR 2021-01-12 20:43:02.476 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/crab_projects/crab_TnP_SingleMuon2016C_zmumu' already exists 
Please change the requestName in the config file
INFO 2021-01-12 20:43:02.479 UTC: 	 Log file is /home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/ZmumuData/crab.log
DEBUG 2021-01-12 20:58:28.485 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-12 20:58:28.486 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-12 20:58:28.486 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-12 20:58:28.487 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
INFO 2021-01-12 20:58:28.490 UTC: 	 Will use CRAB configuration file zmumudata_crab_2016.py
DEBUG 2021-01-12 20:58:28.491 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-01-12 20:58:28.504 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-01-12 20:58:28.505 UTC: 	 Working area '/home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/crab_projects/crab_TnP_SingleMuon2016C_zmumu' already exists 
Please change the requestName in the config file
ERROR 2021-01-12 20:58:28.506 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/crab_projects/crab_TnP_SingleMuon2016C_zmumu' already exists 
Please change the requestName in the config file
INFO 2021-01-12 20:58:28.510 UTC: 	 Log file is /home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/ZmumuData/crab.log
DEBUG 2021-01-12 21:48:32.163 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-12 21:48:32.164 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-12 21:48:32.164 UTC: 	 Executing command: 'status'
DEBUG 2021-01-12 21:48:32.164 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
ERROR 2021-01-12 21:48:32.168 UTC: 	 Error: --verboseErrors is not a valid CRAB project directory.
ERROR 2021-01-12 21:48:32.168 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: --verboseErrors is not a valid CRAB project directory.
INFO 2021-01-12 21:48:32.171 UTC: 	 Log file is /home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/ZmumuData/crab.log
DEBUG 2021-01-14 23:45:20.620 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-14 23:45:20.620 UTC: 	 Running on: Linux t3.unl.edu 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-14 23:45:20.620 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-14 23:45:20.621 UTC: 	 Found CRAB cache file /home/t3-ku/janguian/.crab3
INFO 2021-01-14 23:45:20.624 UTC: 	 Will use CRAB configuration file zmumudata_crab_2018.py
DEBUG 2021-01-14 23:45:20.625 UTC: 	 Loading CRAB configuration file.
DEBUG 2021-01-14 23:45:20.637 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2021-01-14 23:45:20.638 UTC: 	 Working area '/home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/crab_projects/crab_TnP_SingleMuon2018A_zmumu' already exists 
Please change the requestName in the config file
ERROR 2021-01-14 23:45:20.639 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 316, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/ClientUtilities.py", line 397, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/crab_projects/crab_TnP_SingleMuon2018A_zmumu' already exists 
Please change the requestName in the config file
INFO 2021-01-14 23:45:20.642 UTC: 	 Log file is /home/t3-ku/janguian/CMSSW_10_2_5/src/MuonAnalysis/TagAndProbe/test/susy/crab/ZmumuData/crab.log
